#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_WORDS 100
#define MAX_WORD_LEN 1024

typedef struct
{
    int id;
    int row;
    int col;
    int length;
    int dir;
} Slot;

void write_header(FILE *fp);
void write_helper_predicates(FILE *fp);
void write_word_facts(FILE *fp, char words[][MAX_WORD_LEN], int count);
void write_slot_facts(FILE *fp, Slot H[], int hcount, Slot V[], int vcount);
void write_crossword_head(FILE *fp, int hcount, int vcount);
void write_length_constraints(FILE *fp, Slot H[], int hcount, Slot V[], int vcount);
void write_word_constraints(FILE *fp, int hcount, int vcount);
void generate_intersections(FILE *fp, Slot H[], int hcount, Slot V[], int vcount);
void write_unique_constraint(FILE *fp, int hcount, int vcount);
void write_crossword_tail(FILE *fp);
void write_solve_predicate(FILE *fp, int hcount, int vcount);
void read_words(const char *word_file, char words[MAX_WORDS][MAX_WORD_LEN], int *word_count);
void read_pattern(const char *pattern_file, int grid[100][100], int *rows, int *cols);
int slots(int grid[100][100], Slot H_slots[500], Slot V_slots[500], int rows, int cols);

void write_header(FILE *fp)
{
    fprintf(fp, "%% Auto-generated Prolog crossword (step2.pl)\n");
    fprintf(fp, "%% Generated by generator.c\n\n");
}

void write_helper_predicates(FILE *fp)
{
    fprintf(fp,
            "nth(0, [X|_], X).\n"
            "nth(N, [_|T], X) :- N > 0, N1 is N - 1, nth(N1, T, X).\n\n"

            "all_unique([]).\n"
            "all_unique([X|Xs]) :- \\+ member(X, Xs), all_unique(Xs).\n\n"

            "write_word(_, []).\n"
            "write_word(S, [C|Rest]) :- write(S, C), write_word(S, Rest).\n\n"

            "print_slot(S, Word, SlotName) :-\n"
            "    slot(SlotName, _, R, C),\n"
            "    write(S, SlotName), write(S, ' '),\n"
            "    write(S, R), write(S, ' '), write(S, C), write(S, ' '),\n"
            "    write_word(S, Word), nl(S).\n\n");
}

void write_word_facts(FILE *fp, char words[][MAX_WORD_LEN], int count)
{
    for (int i = 0; i < count; i++)
    {
        fprintf(fp, "word([");
        for (int j = 0; words[i][j] != '\0'; j++)
        {
            if (words[i][j] == '\'')
            {
                fprintf(fp, "'\\''");
            }
            else
            {
                fprintf(fp, "'%c'", words[i][j]);
            }
            if (words[i][j + 1] != '\0')
                fprintf(fp, ",");
        }
        fprintf(fp, "]).\n");
    }
    fprintf(fp, "\n");
}

void write_slot_facts(FILE *fp, Slot H[], int hcount, Slot V[], int vcount)
{
    for (int i = 0; i < hcount; i++)
        fprintf(fp, "slot(h%d, horizontal, %d, %d).\n",
                H[i].id, H[i].row, H[i].col);

    for (int i = 0; i < vcount; i++)
        fprintf(fp, "slot(v%d, vertical, %d, %d).\n",
                V[i].id, V[i].row, V[i].col);

    fprintf(fp, "\n");
}

void write_crossword_head(FILE *fp, int hcount, int vcount)
{
    fprintf(fp, "crossword(");
    int first = 1;
    for (int i = 0; i < hcount; i++)
    {
        if (!first)
            fprintf(fp, ",");
        fprintf(fp, "H%d", i);
        first = 0;
    }
    for (int i = 0; i < vcount; i++)
    {
        if (!first)
            fprintf(fp, ",");
        fprintf(fp, "V%d", i);
        first = 0;
    }
    fprintf(fp, ") :-\n");
}

void write_length_constraints(FILE *fp, Slot H[], int hcount, Slot V[], int vcount)
{
    for (int i = 0; i < hcount; i++)
        fprintf(fp, "    length(H%d,%d),\n", i, H[i].length);
    for (int i = 0; i < vcount; i++)
        fprintf(fp, "    length(V%d,%d),\n", i, V[i].length);
}

void write_word_constraints(FILE *fp, int hcount, int vcount)
{
    for (int i = 0; i < hcount; i++)
        fprintf(fp, "    word(H%d),\n", i);
    for (int i = 0; i < vcount; i++)
        fprintf(fp, "    word(V%d),\n", i);
}

void generate_intersections(FILE *fp, Slot H[], int hcount, Slot V[], int vcount)
{
    int varCounter = 0;
    for (int hi = 0; hi < hcount; hi++)
    {
        Slot HS = H[hi];
        for (int vi = 0; vi < vcount; vi++)
        {
            Slot VS = V[vi];
            for (int hpos = 0; hpos < HS.length; hpos++)
            {
                int Hr = HS.row;
                int Hc = HS.col + hpos;
                for (int vpos = 0; vpos < VS.length; vpos++)
                {
                    int Vr = VS.row + vpos;
                    int Vc = VS.col;
                    if (Hr == Vr && Hc == Vc)
                    {
                        fprintf(fp,
                                "    nth(%d, H%d, X%d), nth(%d, V%d, X%d),\n",
                                hpos, HS.id, varCounter,
                                vpos, VS.id, varCounter);
                        varCounter++;
                    }
                }
            }
        }
    }
}

void write_unique_constraint(FILE *fp, int hcount, int vcount)
{
    fprintf(fp, "    all_unique([");
    int first = 1;
    for (int i = 0; i < hcount; i++)
    {
        if (!first)
            fprintf(fp, ",");
        fprintf(fp, "H%d", i);
        first = 0;
    }
    for (int i = 0; i < vcount; i++)
    {
        if (!first)
            fprintf(fp, ",");
        fprintf(fp, "V%d", i);
        first = 0;
    }
    fprintf(fp, "]),\n");
}

void write_crossword_tail(FILE *fp)
{
    fprintf(fp, "    true.\n\n");
}

void write_solve_predicate(FILE *fp, int hcount, int vcount)
{
    fprintf(fp, "solve :-\n    crossword(");
    int first = 1;
    for (int i = 0; i < hcount; i++)
    {
        if (!first)
            fprintf(fp, ",");
        fprintf(fp, "H%d", i);
        first = 0;
    }
    for (int i = 0; i < vcount; i++)
    {
        if (!first)
            fprintf(fp, ",");
        fprintf(fp, "V%d", i);
        first = 0;
    }
    fprintf(fp, "),\n\n");
    fprintf(fp, "    open('selectedwords.txt', write, S),\n\n");

    int total_slots = hcount + vcount;
    int printed = 0;

    for (int i = 0; i < hcount; i++)
    {
        printed++;
        fprintf(fp, "    print_slot(S, H%d, h%d),\n", i, i);
    }
    for (int i = 0; i < vcount; i++)
    {
        printed++;
        fprintf(fp, "    print_slot(S, V%d, v%d),\n", i, i);
    }
    fprintf(fp, "    close(S).\n\n");
}

void read_words(const char *word_file, char words[MAX_WORDS][MAX_WORD_LEN], int *word_count)
{
    FILE *word_p = fopen(word_file, "r");
    if (word_p == NULL)
    {
        perror("Error opening words file");
        exit(1);
    }
    int i = 0;
    char buffer[MAX_WORD_LEN];
    while (i < MAX_WORDS && fscanf(word_p, "%s", buffer) == 1)
    {
        strcpy(words[i], buffer);
        i++;
    }
    *word_count = i;
    fclose(word_p);
}

void read_pattern(const char *pattern_file, int grid[100][100], int *rows, int *cols)
{
    FILE *pattern_p = fopen(pattern_file, "r");
    if (pattern_p == NULL)
    {
        perror("Error opening pattern file");
        exit(1);
    }
    int row_count = 0;
    int col_count = 0;
    int width = 0;
    int ch;
    while ((ch = fgetc(pattern_p)) != EOF)
    {
        if (ch == '0' || ch == '1')
        {
            grid[row_count][col_count] = ch - '0';
            col_count++;
        }
        else if (ch == '\n')
        {
            if (col_count > width)
                width = col_count;
            if (col_count > 0)
                row_count++;
            col_count = 0;
        }
    }
    if (col_count > 0)
    {
        if (col_count > width)
            width = col_count;
        row_count++;
    }
    *rows = row_count;
    *cols = width;
    fclose(pattern_p);
}

int slots(int grid[100][100], Slot H_slots[500], Slot V_slots[500], int rows, int cols)
{
    int hcount = 0;
    int vcount = 0;
    for (int r = 0; r < rows; r++)
    {
        int c = 0;
        while (c < cols)
        {
            if (grid[r][c] == 1)
            {
                int start = c;
                int len = 0;
                while (c < cols && grid[r][c] == 1)
                {
                    len++;
                    c++;
                }
                if (len >= 2)
                {
                    H_slots[hcount].id = hcount;
                    H_slots[hcount].row = r;
                    H_slots[hcount].col = start;
                    H_slots[hcount].length = len;
                    H_slots[hcount].dir = 0;
                    hcount++;
                }
            }
            else
            {
                c++;
            }
        }
    }
    for (int c = 0; c < cols; c++)
    {
        int r = 0;
        while (r < rows)
        {
            if (grid[r][c] == 1)
            {
                int start = r;
                int len = 0;
                while (r < rows && grid[r][c] == 1)
                {
                    len++;
                    r++;
                }
                if (len >= 2)
                {
                    V_slots[vcount].id = vcount;
                    V_slots[vcount].row = start;
                    V_slots[vcount].col = c;
                    V_slots[vcount].length = len;
                    V_slots[vcount].dir = 1;
                    vcount++;
                }
            }
            else
            {
                r++;
            }
        }
    }
    return (hcount << 16) | (vcount & 0xFFFF);
}

int main(int argc, char *argv[])
{
    if (argc < 3)
    {
        fprintf(stderr, "Usage: %s words.txt binpattern.txt\n", argv[0]);
        return 1;
    }
    char *word_file = argv[1];
    char *pattern_file = argv[2];

    char words[MAX_WORDS][MAX_WORD_LEN];
    int grid[100][100] = {{0}};
    Slot H[500];
    Slot V[500];
    int word_count = 0;
    int rows = 0;
    int cols = 0;
    int hcount = 0;
    int vcount = 0;

    read_words(word_file, words, &word_count);
    read_pattern(pattern_file, grid, &rows, &cols);

    int packed = slots(grid, H, V, rows, cols);
    hcount = (packed >> 16) & 0xFFFF;
    vcount = packed & 0xFFFF;

    FILE *fp = fopen("step2.pl", "w");
    if (fp == NULL)
    {
        perror("Error creating step2.pl");
        return 1;
    }

    write_header(fp);
    write_helper_predicates(fp);
    write_word_facts(fp, words, word_count);
    write_slot_facts(fp, H, hcount, V, vcount);
    write_crossword_head(fp, hcount, vcount);
    write_length_constraints(fp, H, hcount, V, vcount);
    write_word_constraints(fp, hcount, vcount);
    generate_intersections(fp, H, hcount, V, vcount);
    write_unique_constraint(fp, hcount, vcount);
    write_crossword_tail(fp);
    write_solve_predicate(fp, hcount, vcount);

    fclose(fp);
    printf("Generated step2.pl: %d words, %d horizontal, %d vertical, grid %dx%d\n",
           word_count, hcount, vcount, rows, cols);

    return 0;
}